import Foundation

enum GlossaryMix {
    static let terms: [Term] = [

        // MARK: Mixer

        Term(id: "mixer", name: "MIXER", cat: .mixer,
             isA: "The page with a vertical strip for every track.",
             does: "Sets each track's volume, pan, effects and routing.",
             when: "After the arrangement works. Mixing before you've finished writing is polishing something that will change.",
             found: [DAWLocation(daw: "ABLETON", path: "Mixer columns in Session view, or the track headers"),
                     DAWLocation(daw: "FL STUDIO", path: "F9"),
                     DAWLocation(daw: "LOGIC", path: "X key")],
             related: ["channelStrip", "fader", "bus", "send"]),

        Term(id: "channelStrip", name: "CHANNEL STRIP", cat: .mixer,
             isA: "One track's controls in the mixer.",
             does: "Input gain, EQ, dynamics, sends, pan, fader, output routing — top to bottom.",
             when: "Signal flows top to bottom. Plugins process in the order they're listed.",
             related: ["mixer", "fader", "pan", "send"]),

        Term(id: "fader", name: "FADER", cat: .mixer,
             aka: ["volume", "level"],
             isA: "The volume slider for a track.",
             does: "Sets how loud that track is in the mix.",
             when: "Your first and best mixing tool. Most 'mix problems' are balance problems.",
             related: ["gainStaging", "mixer", "automation"]),

        Term(id: "gainStaging", name: "GAIN STAGING", cat: .mixer,
             isA: "Keeping levels sensible at every point in the chain.",
             does: "Prevents clipping, plugin distortion and a squashed master.",
             when: "Loudest element peaking −8 to −6 dB, master peaking around −6 with nothing on it.",
             related: ["headroom", "clipping", "fader", "peak"]),

        Term(id: "headroom", name: "HEADROOM", cat: .mixer,
             isA: "The space between your loudest peak and 0 dB.",
             does: "Gives the mastering stage room to work and stops digital clipping.",
             when: "Leave 6 dB. If the master is hot, pull all faders down together, not the master fader.",
             related: ["gainStaging", "clipping", "peak", "limiter"]),

        Term(id: "clipping", name: "CLIPPING", cat: .mixer,
             aka: ["red", "overs"],
             isA: "Signal exceeding 0 dBFS.",
             does: "Flattens the waveform tops. Digitally this is harsh, brittle distortion.",
             when: "If the master meter goes red, fix it. Deliberate soft clipping on drums is a different, intentional thing.",
             related: ["headroom", "peak", "limiter", "saturation"]),

        Term(id: "peak", name: "PEAK vs RMS", cat: .mixer,
             isA: "Two ways of measuring level.",
             does: "Peak is the highest instantaneous sample. RMS is the average — much closer to how loud it sounds.",
             when: "Peak for avoiding clipping, RMS/LUFS for judging loudness.",
             related: ["lufs", "clipping", "headroom"]),

        Term(id: "pan", name: "PAN", cat: .mixer,
             isA: "Position between left and right.",
             does: "Places a sound in the stereo field.",
             when: "Kick, snare, bass and lead centred. Hats and perc 10–25% out. Ear candy wide.",
             related: ["stereo", "mono", "width", "midSide"]),

        Term(id: "stereo", name: "STEREO", cat: .mixer,
             isA: "Two channels, left and right.",
             does: "Lets sounds occupy different horizontal positions, creating width.",
             when: "Everything above ~150 Hz can be stereo. Below that, keep it mono.",
             related: ["mono", "pan", "width", "midSide"]),

        Term(id: "mono", name: "MONO", cat: .mixer,
             isA: "A single channel, dead centre.",
             does: "Same signal in both speakers, so it can't cancel or shift.",
             when: "Kick, bass and 808 always. Check the whole mix in mono once per session — phones and clubs are near-mono.",
             related: ["stereo", "phase", "width"]),

        Term(id: "width", name: "STEREO WIDTH / WIDENER", cat: .mixer,
             isA: "How far a sound spreads left to right.",
             does: "Wideners make L and R slightly different, which the ear reads as space.",
             when: "On pads, backing vocals and ear candy. Never on bass. Always check the result in mono.",
             related: ["stereo", "midSide", "mono", "phase"]),

        Term(id: "midSide", name: "MID / SIDE", cat: .mixer,
             aka: ["M/S"],
             isA: "Splitting a stereo signal into what's centred and what's not.",
             does: "Lets you process the middle and the sides separately.",
             when: "High-pass the sides to keep bass centred. Boost the sides' highs for air without touching the vocal.",
             related: ["stereo", "width", "eq", "mono"]),

        Term(id: "bus", name: "BUS / GROUP", cat: .mixer,
             aka: ["submix", "group", "folder", "aux"],
             isA: "A channel several tracks feed into.",
             does: "One fader and one set of plugins for a whole group.",
             when: "Drums bus, music bus, vocal bus. Light compression on a drum bus glues the kit together.",
             found: [DAWLocation(daw: "ABLETON", path: "Select tracks → Cmd+G to group"),
                     DAWLocation(daw: "FL STUDIO", path: "Route mixer inserts to a spare insert with the output arrow"),
                     DAWLocation(daw: "LOGIC", path: "Select tracks → Summing Stack (Cmd+Shift+D)")],
             related: ["send", "return", "parallel", "master"]),

        Term(id: "send", name: "SEND", cat: .mixer,
             isA: "A copy of a track's signal routed somewhere else.",
             does: "Feeds a shared effect without removing the dry signal from the main path.",
             when: "Reverb and delay. One reverb on a return, several tracks sending to it, one coherent room.",
             related: ["return", "bus", "reverb", "delay", "wetDry"]),

        Term(id: "return", name: "RETURN / AUX / FX TRACK", cat: .mixer,
             isA: "The channel a send arrives at.",
             does: "Holds the shared effect, 100% wet, with its own fader.",
             when: "Set the effect fully wet on the return and control the amount with the send knobs.",
             related: ["send", "bus", "reverb", "wetDry"]),

        Term(id: "parallel", name: "PARALLEL PROCESSING", cat: .mixer,
             aka: ["new york compression"],
             isA: "Blending a heavily processed copy under the original.",
             does: "Gives you the density of extreme processing while the original keeps its punch.",
             when: "Drums: send to a bus, compress 10:1 with 10+ dB reduction, blend underneath.",
             related: ["compressor", "send", "bus", "saturation"]),

        Term(id: "master", name: "MASTER / STEREO OUT", cat: .mixer,
             isA: "The final channel everything passes through.",
             does: "The last stop before your speakers and before export.",
             when: "Keep it empty while writing. A limiter here early hides every balance problem.",
             related: ["limiter", "headroom", "lufs", "bus"]),

        Term(id: "solo", name: "SOLO / MUTE", cat: .mixer,
             isA: "Hear one track alone / silence one track.",
             does: "Isolates or removes a track from the mix.",
             when: "Solo to identify a problem, then unsolo to fix it. Mute is also the fastest way to arrange.",
             related: ["mixer", "arrangement", "fader"]),

        // MARK: Effects

        Term(id: "eq", name: "EQ / EQUALISER", cat: .effect,
             isA: "A tool that turns specific frequency ranges up or down.",
             does: "Gives each instrument its own space in the spectrum.",
             when: "High-pass everything that isn't kick or bass. Cut problems narrowly, boost character widely.",
             found: [DAWLocation(daw: "ABLETON", path: "EQ Eight"),
                     DAWLocation(daw: "FL STUDIO", path: "Fruity Parametric EQ 2"),
                     DAWLocation(daw: "LOGIC", path: "Channel EQ — top of every strip")],
             related: ["highPass", "lowPass", "bell", "shelf", "qFactor", "mud"]),

        Term(id: "highPass", name: "HIGH-PASS / LOW CUT", cat: .effect,
             aka: ["HPF", "low cut"],
             isA: "A filter that removes low frequencies.",
             does: "Everything below the cutoff is rolled off; the highs pass through.",
             when: "On everything except kick and bass. 100–200 Hz. The single highest-value move in mixing.",
             related: ["eq", "lowPass", "mud", "filter"]),

        Term(id: "lowPass", name: "LOW-PASS / HIGH CUT", cat: .effect,
             aka: ["LPF", "high cut"],
             isA: "A filter that removes high frequencies.",
             does: "Darkens a sound and pushes it further back in the mix.",
             when: "Taming harshness, making a part sit behind another, or automating a filter sweep in a build.",
             related: ["eq", "highPass", "filter", "automation"]),

        Term(id: "bell", name: "BELL / PEAK BAND", cat: .effect,
             isA: "An EQ band that boosts or cuts around a centre frequency.",
             does: "Affects a hump of frequencies whose width is set by Q.",
             when: "The workhorse EQ shape. Narrow to remove a resonance, wide to add character.",
             related: ["eq", "qFactor", "shelf"]),

        Term(id: "shelf", name: "SHELF", cat: .effect,
             isA: "An EQ band that lifts or drops everything above or below a point.",
             does: "A gentle tilt rather than a hump.",
             when: "High shelf +2 dB at 10 kHz for air. Low shelf −2 dB at 200 Hz to de-mud a whole track.",
             related: ["eq", "bell", "highPass"]),

        Term(id: "qFactor", name: "Q / BANDWIDTH", cat: .effect,
             isA: "How wide an EQ band is.",
             does: "High Q = narrow and surgical. Low Q = wide and musical.",
             when: "High Q for cuts, low Q for boosts. Almost always.",
             related: ["eq", "bell"]),

        Term(id: "mud", name: "MUD", cat: .effect,
             isA: "Cloudy build-up in the 150–400 Hz range.",
             does: "Comes from many sounds all having energy in the same low-mid region.",
             when: "If your mix sounds like a blanket over it: high-pass everything non-bass and cut 200–300 Hz on the worst offenders.",
             related: ["eq", "highPass", "voicing"]),

        Term(id: "compressor", name: "COMPRESSOR", cat: .effect,
             isA: "An automatic volume control that turns loud things down.",
             does: "Reduces the gap between the quietest and loudest parts so you can raise the whole thing.",
             when: "3–5 dB of reduction on drums, bass and vocals. Watch the gain reduction meter, not the numbers.",
             related: ["threshold", "ratio", "attack", "release", "makeupGain", "limiter", "sidechain"]),

        Term(id: "threshold", name: "THRESHOLD", cat: .effect,
             isA: "The level at which a compressor starts working.",
             does: "Anything above it gets turned down; anything below passes untouched.",
             when: "Lower it until the gain reduction meter shows 3–5 dB on the loud hits.",
             related: ["compressor", "ratio"]),

        Term(id: "ratio", name: "RATIO", cat: .effect,
             isA: "How hard the compressor clamps down.",
             does: "4:1 means 4 dB over the threshold becomes 1 dB over.",
             when: "2:1 gentle glue, 4:1 standard control, 10:1+ is limiting.",
             related: ["compressor", "threshold", "limiter"]),

        Term(id: "attack", name: "ATTACK", cat: .effect,
             isA: "How fast the compressor reacts.",
             does: "Slow attack lets the transient through before clamping — more punch. Fast attack squashes it — more control.",
             when: "10–30 ms on drums if you want punch. 0–3 ms if you want them tamed and even.",
             related: ["compressor", "release", "transient"]),

        Term(id: "release", name: "RELEASE", cat: .effect,
             isA: "How fast the compressor lets go.",
             does: "Too fast causes audible pumping, too slow means it never recovers between hits.",
             when: "Time it to the tempo — it should recover just before the next hit.",
             related: ["compressor", "attack", "pumping"]),

        Term(id: "makeupGain", name: "MAKEUP GAIN", cat: .effect,
             aka: ["output gain"],
             isA: "Volume added after compression.",
             does: "Brings the now-quieter signal back up. This is the part that makes compression sound 'bigger'.",
             when: "Match the bypassed level so you're judging the compression, not the volume increase.",
             related: ["compressor", "gainStaging"]),

        Term(id: "limiter", name: "LIMITER", cat: .effect,
             isA: "A compressor with an infinite ratio.",
             does: "Sets a hard ceiling nothing gets past.",
             when: "Last plugin on the master, ceiling at −1 dB. Not while you're still writing.",
             related: ["compressor", "master", "clipping", "lufs", "truePeak"]),

        Term(id: "sidechain", name: "SIDECHAIN", cat: .effect,
             aka: ["ducking"],
             isA: "Compression triggered by a different track.",
             does: "Ducks one sound out of the way every time another one hits.",
             when: "Bass ducking under the kick. Also reverb ducking under a vocal, pads under a snare.",
             found: [DAWLocation(daw: "ABLETON", path: "Compressor → sidechain arrow, bottom left"),
                     DAWLocation(daw: "FL STUDIO", path: "Right-click the kick's mixer track → Sidechain to this track"),
                     DAWLocation(daw: "LOGIC", path: "Compressor → Side Chain menu, top right")],
             related: ["compressor", "ducking", "pumping", "808", "kick"]),

        Term(id: "ducking", name: "DUCKING", cat: .effect,
             isA: "One sound dropping in level for another.",
             does: "Creates room in a specific moment instead of turning something down forever.",
             when: "Kick and bass, vocal and instrumental, reverb and lead.",
             related: ["sidechain", "compressor"]),

        Term(id: "pumping", name: "PUMPING", cat: .effect,
             isA: "Audible breathing from a compressor's release.",
             does: "Volume visibly rising back up between hits.",
             when: "A mistake on a mix bus. A signature sound in French house and EDM when done on purpose.",
             related: ["sidechain", "release", "compressor"]),

        Term(id: "reverb", name: "REVERB", cat: .effect,
             isA: "Simulated room sound.",
             does: "Adds reflections that place a sound in a space and push it backwards.",
             when: "On a send, never as ten separate inserts. High-pass the tail below 300 Hz. Keep it off the kick and bass.",
             related: ["preDelay", "send", "return", "wetDry", "delay"]),

        Term(id: "preDelay", name: "PRE-DELAY", cat: .effect,
             isA: "A gap before the reverb starts.",
             does: "Keeps the dry source clear and up front while still placing it in a large space.",
             when: "20–40 ms on vocals and leads. Massively underused and instantly improves clarity.",
             related: ["reverb", "delay"]),

        Term(id: "delay", name: "DELAY / ECHO", cat: .effect,
             isA: "Repeats of the original sound.",
             does: "Adds rhythm, width and depth depending on the time and feedback.",
             when: "Sync to tempo — 1/8 dotted for the classic push, 1/4 for wide echoes, 60–120 ms slapback to thicken.",
             related: ["feedback", "reverb", "send", "wetDry"]),

        Term(id: "feedback", name: "FEEDBACK", cat: .effect,
             aka: ["repeats"],
             isA: "How much of a delay's output goes back into its input.",
             does: "Controls how many repeats you get before they die out.",
             when: "Two or three repeats is usually enough. High feedback plus a filter is a creative effect.",
             related: ["delay", "reverb"]),

        Term(id: "wetDry", name: "WET / DRY", cat: .effect,
             aka: ["mix knob"],
             isA: "The balance between the processed and unprocessed signal.",
             does: "100% wet = only the effect. 0% = only the original.",
             when: "On an insert, keep it low (10–25%). On a return, set it to 100% wet and use the send to control the amount.",
             related: ["send", "return", "reverb", "delay"]),

        Term(id: "saturation", name: "SATURATION / DRIVE", cat: .effect,
             aka: ["distortion", "tape", "warmth"],
             isA: "Gentle, musical distortion.",
             does: "Adds harmonics, which makes a sound feel louder and denser without raising its peak level.",
             when: "On a bass that disappears on phones, on a drum bus for glue, on anything that sounds sterile.",
             related: ["clipping", "compressor", "parallel"]),

        Term(id: "filter", name: "FILTER", cat: .effect,
             isA: "A frequency-removing tool with a movable cutoff.",
             does: "Low-pass removes highs, high-pass removes lows, band-pass keeps a middle window.",
             when: "The most automated parameter in electronic music. Close it through a build, snap it open on the drop.",
             related: ["highPass", "lowPass", "automation", "resonance"]),

        Term(id: "resonance", name: "RESONANCE", cat: .synth,
             aka: ["Q", "emphasis"],
             isA: "A boost right at a filter's cutoff point.",
             does: "Emphasises the frequencies at the edge of the filter.",
             when: "A little adds character and makes filter sweeps audible. A lot whistles and can get painful.",
             related: ["filter", "qFactor", "synth"]),

        // MARK: Synth

        Term(id: "synth", name: "SYNTHESISER", cat: .synth,
             isA: "An instrument that generates sound from scratch.",
             does: "Oscillators make raw tone, filters shape it, envelopes control it over time.",
             when: "Bass, pads and leads. Samples for drums and acoustic instruments.",
             related: ["oscillator", "filter", "adsr", "lfo", "preset"]),

        Term(id: "oscillator", name: "OSCILLATOR / OSC", cat: .synth,
             aka: ["waveform"],
             isA: "The part that generates the raw tone.",
             does: "Saw is bright and full, square is hollow and retro, sine is pure and bassy, triangle is soft.",
             when: "Saw for basses and leads, sine for subs, square for retro plucks.",
             related: ["synth", "filter", "detune"]),

        Term(id: "detune", name: "DETUNE / UNISON", cat: .synth,
             isA: "Slightly mistuned copies of the same oscillator.",
             does: "The tiny pitch differences beat against each other, creating thickness and width.",
             when: "Supersaw leads and big pads. Keep it off basses — detune below 100 Hz turns to mush.",
             related: ["oscillator", "synth", "width"]),

        Term(id: "adsr", name: "ADSR / ENVELOPE", cat: .synth,
             aka: ["envelope", "amp env"],
             isA: "The shape of a sound over time.",
             does: "Attack = how fast it arrives, Decay = fall to Sustain = held level, Release = fade after you let go.",
             when: "Fast attack for percussive parts, slow attack for swelling pads. Short release keeps space for drums.",
             related: ["synth", "envelope", "attack", "release"]),

        Term(id: "envelope", name: "ENVELOPE", cat: .synth,
             isA: "Any control that changes automatically over the life of a note.",
             does: "Applied to volume it's ADSR. Applied to a filter it's a sweep on every note.",
             when: "A filter envelope is what gives a pluck its 'pyoo' and a bass its bite.",
             related: ["adsr", "filter", "modulation"]),

        Term(id: "lfo", name: "LFO", cat: .synth,
             aka: ["low frequency oscillator"],
             isA: "A slow wave used to move something automatically.",
             does: "On pitch it's vibrato, on volume it's tremolo, on a filter it's the classic wobble.",
             when: "Adding movement to a static pad, or building a wobble bass. Sync it to the tempo.",
             related: ["modulation", "filter", "synth"]),

        Term(id: "modulation", name: "MODULATION", cat: .synth,
             isA: "One control moving another.",
             does: "LFOs, envelopes and macros all modulate parameters so a sound isn't static.",
             when: "Any time a synth part sounds lifeless after four bars.",
             related: ["lfo", "envelope", "automation"]),

        Term(id: "preset", name: "PRESET / PATCH", cat: .synth,
             isA: "A saved synth or plugin setting.",
             does: "Recalls someone else's sound design instantly.",
             when: "Start from one that's 70% right, then change the filter cutoff, attack and release. That's most of sound design.",
             related: ["synth", "adsr", "filter"]),

        Term(id: "sampler", name: "SAMPLER", cat: .synth,
             isA: "An instrument that plays back audio files across a keyboard.",
             does: "Maps a sample to keys, pitching it up and down, with looping, slicing and envelopes.",
             when: "Drums (one-shots on pads), chopped samples, and any acoustic instrument.",
             found: [DAWLocation(daw: "ABLETON", path: "Simpler / Sampler / Drum Rack"),
                     DAWLocation(daw: "FL STUDIO", path: "Channel sampler / Slicex / FPC"),
                     DAWLocation(daw: "LOGIC", path: "Quick Sampler / Sampler / Drum Machine Designer")],
             related: ["oneShot", "chop", "sample", "transpose"]),

        Term(id: "oneShot", name: "ONE-SHOT", cat: .synth,
             isA: "A single, short, non-looping sample.",
             does: "Plays once from start to finish when triggered.",
             when: "Every drum hit you place is a one-shot. Contrast with a loop, which is a bar or more of audio.",
             related: ["sampler", "sample", "kick"]),

        Term(id: "sample", name: "SAMPLE", cat: .synth,
             isA: "Any piece of recorded audio you use as material.",
             does: "Either a one-shot, a loop, or a section of a record you chop.",
             when: "Everywhere. Sound selection matters more than processing.",
             related: ["oneShot", "sampler", "chop", "sampleLibrary"]),

        Term(id: "sampleLibrary", name: "SAMPLE PACK / LIBRARY", cat: .file,
             isA: "A folder of sounds licensed for you to use.",
             does: "Gives you drums, loops and one-shots without recording anything.",
             when: "Pick ten kicks, ten snares and ten hats you like and use only those for a month. You'll finish more.",
             related: ["sample", "oneShot", "tuning"]),

        Term(id: "tuning", name: "TUNING (DRUMS)", cat: .synth,
             isA: "Pitching a drum sample to your key.",
             does: "A kick and 808 with a clear pitch will clash with the track if they're in the wrong key.",
             when: "Pitch the kick to the root note or its fifth. Tune the 808 to the actual notes of your bassline.",
             related: ["transpose", "808", "kick", "rootNote"]),

        Term(id: "layering", name: "LAYERING", cat: .synth,
             isA: "Stacking two sounds to be heard as one.",
             does: "Each layer contributes something the other doesn't — weight from one, click from the other.",
             when: "Kicks, snares, basses and leads. Two layers with distinct jobs, EQ'd so they don't overlap.",
             related: ["phase", "polarity", "eq", "transient"]),

        Term(id: "phase", name: "PHASE", cat: .mixer,
             isA: "The timing relationship between two versions of a signal.",
             does: "Out-of-phase copies cancel each other, making the result thinner instead of bigger.",
             when: "If two layered kicks sound weaker than one alone, that's phase. Also why mixes collapse in mono.",
             related: ["polarity", "layering", "mono"]),

        Term(id: "polarity", name: "POLARITY (Ø)", cat: .mixer,
             aka: ["phase flip", "invert"],
             isA: "A button that flips a signal upside down.",
             does: "Inverts the waveform, which can fix cancellation between two layers.",
             when: "On layered drums. Flip it, listen. If it suddenly gets fuller, leave it flipped.",
             related: ["phase", "layering"]),

        Term(id: "bass", name: "BASS", cat: .theory,
             isA: "The low melodic instrument.",
             does: "Belongs to both the rhythm section and the harmony — it's why a beat sounds finished.",
             when: "Root notes following the kick pattern. C1–C3. Mono, centred, sidechained to the kick.",
             related: ["808", "sub", "sidechain", "rootNote"]),

        Term(id: "808", name: "808", cat: .theory,
             isA: "A long, pitched sine kick from the TR-808 drum machine.",
             does: "Acts as both the kick and the bassline at once in trap and drill.",
             when: "Tune it to your key, keep the notes short enough not to overlap, and don't stack a second kick on top of it.",
             related: ["bass", "sub", "sidechain", "kick", "tuning"]),

        Term(id: "sub", name: "SUB BASS", cat: .theory,
             isA: "Energy below about 60 Hz.",
             does: "Felt more than heard. Invisible on laptop and phone speakers.",
             when: "Add a distorted or octave-up layer so the bassline still reads on small speakers.",
             related: ["bass", "808", "layering", "saturation"]),

        Term(id: "pad", name: "PAD", cat: .synth,
             isA: "A sustained, soft, chordal sound.",
             does: "Fills space behind everything else and holds the harmony.",
             when: "When a mix feels empty between the drums and the melody. Slow attack, long release, high-passed.",
             related: ["chord", "adsr", "reverb", "arpeggio"]),

        // MARK: Files & output

        Term(id: "export", name: "EXPORT / BOUNCE", cat: .file,
             aka: ["render", "bounce", "freeze"],
             isA: "Writing your project out as an audio file.",
             does: "Renders the selected range through the master to WAV or MP3.",
             when: "WAV 24-bit for anyone else, MP3 320 for casual listening. Check the export range every time.",
             found: [DAWLocation(daw: "ABLETON", path: "Cmd+Shift+R — Export Audio/Video"),
                     DAWLocation(daw: "FL STUDIO", path: "File → Export → WAV"),
                     DAWLocation(daw: "LOGIC", path: "Cmd+B — Bounce Project or Section")],
             related: ["bounce", "stems", "sampleRate", "dither", "lufs"]),

        Term(id: "bounce", name: "BOUNCE IN PLACE", cat: .file,
             aka: ["freeze and flatten", "render to audio"],
             isA: "Turning a MIDI track and its plugins into plain audio.",
             does: "Frees CPU and locks the sound in.",
             when: "When your session is stuttering, or before sending a project to someone without your plugins.",
             related: ["export", "stems", "midi"]),

        Term(id: "stems", name: "STEMS", cat: .file,
             isA: "Each track or group exported separately.",
             does: "Gives another person your parts to mix or rework.",
             when: "All from bar 1, all the same length, no master processing, named clearly.",
             related: ["export", "bus", "master"]),

        Term(id: "sampleRate", name: "SAMPLE RATE / BIT DEPTH", cat: .file,
             isA: "How many times per second audio is measured, and at what resolution.",
             does: "44.1 kHz / 24-bit is the standard for music. 48 kHz for anything going to video.",
             when: "Set it at project creation and never change it mid-project.",
             related: ["export", "dither"]),

        Term(id: "dither", name: "DITHER", cat: .file,
             isA: "Tiny noise added when reducing bit depth.",
             does: "Masks the distortion that would otherwise happen going from 24-bit to 16-bit.",
             when: "Only on a final 16-bit master. Never on stems, never twice.",
             related: ["export", "sampleRate", "master"]),

        Term(id: "lufs", name: "LUFS", cat: .file,
             aka: ["loudness", "integrated"],
             isA: "A measurement of perceived loudness over time.",
             does: "Streaming platforms normalise everything to about −14 LUFS.",
             when: "Aim for −9 to −14 integrated. Mastering louder than that just makes you more squashed at the same playback level.",
             related: ["truePeak", "limiter", "master", "peak"]),

        Term(id: "truePeak", name: "TRUE PEAK", cat: .file,
             isA: "The real peak level after digital-to-analogue conversion.",
             does: "Can be higher than the sample peak, causing distortion on playback and after MP3 encoding.",
             when: "Set your limiter's ceiling to −1.0 dBTP to leave room for it.",
             related: ["limiter", "lufs", "clipping", "export"]),

        Term(id: "reference", name: "REFERENCE TRACK", cat: .file,
             isA: "A finished commercial song used as a measuring stick.",
             does: "Shows you honestly where your low end, brightness and levels sit.",
             when: "Import it, turn it DOWN to match your mix's loudness, and A/B every 15 minutes.",
             related: ["translation", "lufs", "master"]),

        Term(id: "translation", name: "TRANSLATION", cat: .file,
             isA: "How well a mix holds up on different speakers.",
             does: "A mix that only works on your headphones hasn't translated.",
             when: "Check on phone speaker, car, earbuds and laptop. If the midrange is right, it'll translate.",
             related: ["reference", "mono", "eq"])
    ]
}
