import Foundation

enum GlossaryCore {
    static let terms: [Term] = [

        // MARK: Transport

        Term(id: "daw", name: "DAW", cat: .transport,
             aka: ["digital audio workstation"],
             isA: "The program you make music in.",
             does: "Combines a clock, a multitrack recorder, a note editor and a mixer in one window.",
             when: "Always. Ableton, FL Studio, Logic, Reaper, Pro Tools, Bitwig and Studio One are all the same four ideas with different layouts.",
             related: ["mixer", "track", "pianoRoll"]),

        Term(id: "bpm", name: "BPM / TEMPO", cat: .transport,
             aka: ["beats per minute", "speed"],
             isA: "How many beats happen per minute.",
             does: "Sets the speed of the grid, and therefore of everything in the project.",
             when: "First thing in a new project. 90 for rap, 124 for house, 140 for trap, 170 for drum & bass.",
             found: [DAWLocation(daw: "ABLETON", path: "Top-left of the transport bar"),
                     DAWLocation(daw: "FL STUDIO", path: "Top toolbar, the big number"),
                     DAWLocation(daw: "LOGIC", path: "LCD display, centre of the control bar")],
             related: ["bar", "timeSignature", "warp"]),

        Term(id: "transport", name: "TRANSPORT", cat: .transport,
             isA: "The play/stop/record/loop controls.",
             does: "Moves the playhead through the project.",
             when: "Constantly. Spacebar is play/stop in every DAW.",
             related: ["loop", "metronome", "playhead"]),

        Term(id: "playhead", name: "PLAYHEAD", cat: .transport,
             aka: ["cursor", "position"],
             isA: "The vertical line showing where you are in time.",
             does: "Marks the point currently being played back.",
             when: "Click the timeline to move it. Most DAWs return it to where you started when you stop — hold Shift to keep it where it stopped.",
             related: ["transport", "loop"]),

        Term(id: "loop", name: "LOOP / CYCLE", cat: .transport,
             aka: ["cycle", "repeat"],
             isA: "A region that repeats forever during playback.",
             does: "Plays a chosen range over and over so you can edit while it runs.",
             when: "Whenever you're building. Loop bars 1–4 and never turn it off while writing.",
             found: [DAWLocation(daw: "ABLETON", path: "Loop brace above the arrangement timeline"),
                     DAWLocation(daw: "FL STUDIO", path: "Playlist time markers / pattern mode loops by default"),
                     DAWLocation(daw: "LOGIC", path: "Cycle area in the ruler — C key")],
             related: ["transport", "bar"]),

        Term(id: "metronome", name: "METRONOME / CLICK", cat: .transport,
             isA: "A tick on every beat.",
             does: "Gives you the grid audibly so you can play in time.",
             when: "On when recording anything played by hand. Off when auditioning a mix — it colours your judgement.",
             related: ["bpm", "quantize"]),

        Term(id: "timeSignature", name: "TIME SIGNATURE", cat: .transport,
             aka: ["4/4", "meter"],
             isA: "How many beats are in a bar.",
             does: "4/4 means four beats per bar and is the default for nearly all popular music. 3/4 is a waltz, 6/8 has a rolling triplet feel.",
             when: "Leave it at 4/4 unless you specifically want an unusual feel. Changing it later re-grids the whole project.",
             related: ["bar", "bpm"]),

        Term(id: "bar", name: "BAR / MEASURE", cat: .transport,
             isA: "A group of four beats.",
             does: "The unit everything in music is counted in. Loops are 1, 2, 4 or 8 bars. Sections are 8 or 16.",
             when: "Every time you think about length. If something feels wrong structurally, count the bars — it's usually an odd number where it should be even.",
             related: ["timeSignature", "section", "arrangement"]),

        // MARK: Editing

        Term(id: "pianoRoll", name: "PIANO ROLL", cat: .editing,
             aka: ["midi editor", "note editor"],
             isA: "The grid where you draw notes.",
             does: "Time runs left to right, pitch runs bottom to top. Each bar you draw is a note.",
             when: "Any time you're writing melodies, chords, basslines or programmed drums.",
             found: [DAWLocation(daw: "ABLETON", path: "Double-click a MIDI clip — editor opens at the bottom"),
                     DAWLocation(daw: "FL STUDIO", path: "Right-click a channel → Piano roll (F7)"),
                     DAWLocation(daw: "LOGIC", path: "Double-click a MIDI region, or P key")],
             related: ["midi", "velocity", "quantize", "scale"]),

        Term(id: "midi", name: "MIDI", cat: .editing,
             isA: "Note data, not sound.",
             does: "Stores which note, when, how long and how hard — then tells an instrument to play it. Change the instrument and the same part plays with a new sound.",
             when: "For anything you want to be able to edit after the fact. Which is nearly everything you write yourself.",
             related: ["pianoRoll", "audioTrack", "velocity", "synth"]),

        Term(id: "audioTrack", name: "AUDIO TRACK", cat: .editing,
             aka: ["wav", "sample track"],
             isA: "A lane holding actual recorded sound.",
             does: "Plays back a waveform. Editing means cutting, fading, stretching or pitching — not changing notes.",
             when: "Recordings, samples, loops, vocals, anything you didn't write as notes.",
             related: ["midi", "warp", "sampler", "chop"]),

        Term(id: "clip", name: "CLIP / REGION", cat: .editing,
             aka: ["region", "item", "pattern"],
             isA: "A block of content sitting on a track.",
             does: "Contains either notes or audio, and can be moved, copied, looped and resized as a unit.",
             when: "The thing you drag around when arranging. Duplicate with Cmd/Ctrl+D.",
             related: ["track", "arrangement", "midi"]),

        Term(id: "track", name: "TRACK / CHANNEL", cat: .editing,
             isA: "One lane holding one sound source.",
             does: "Holds clips, gets exactly one mixer channel with its own volume, pan and effects.",
             when: "One per sound. Kick, snare and hats on separate tracks, always.",
             related: ["clip", "channelStrip", "bus"]),

        Term(id: "quantize", name: "QUANTIZE", cat: .editing,
             isA: "Snapping already-placed notes onto the grid.",
             does: "Drags every selected note to the nearest grid line of the chosen value.",
             when: "After playing something in by hand. Use 50–80% strength to tighten without killing the feel.",
             found: [DAWLocation(daw: "ABLETON", path: "Cmd+U · settings under Cmd+Shift+U"),
                     DAWLocation(daw: "FL STUDIO", path: "Piano roll → Alt+Q for the quantize dialog"),
                     DAWLocation(daw: "LOGIC", path: "Region/Note inspector → Quantize + Q-Strength")],
             related: ["snap", "swing", "groove", "humanize"]),

        Term(id: "snap", name: "SNAP / GRID", cat: .editing,
             isA: "Magnetism to the grid as you draw.",
             does: "Forces anything you place onto the nearest division — 1/4, 1/8, 1/16, triplets.",
             when: "On at 1/16 for drums by default. Turn it off to nudge a hit slightly early or late for feel.",
             related: ["quantize", "bar"]),

        Term(id: "velocity", name: "VELOCITY", cat: .editing,
             aka: ["accent", "note strength"],
             isA: "How hard a note is hit, 0–127.",
             does: "Usually controls volume, and on good instruments also tone — harder hits are brighter.",
             when: "Always. Flat velocity is the main reason programmed drums sound programmed.",
             found: [DAWLocation(daw: "ABLETON", path: "Velocity lane below the piano roll"),
                     DAWLocation(daw: "FL STUDIO", path: "Bar height in the event editor under the roll"),
                     DAWLocation(daw: "LOGIC", path: "Note colour + the velocity slider in the inspector")],
             related: ["ghostNote", "humanize", "accent", "pianoRoll"]),

        Term(id: "accent", name: "ACCENT", cat: .editing,
             isA: "A deliberately louder hit.",
             does: "Pulls the ear to a specific step.",
             when: "On the four downbeats of a hat pattern. It's what makes a pattern breathe.",
             related: ["velocity", "ghostNote"]),

        Term(id: "ghostNote", name: "GHOST NOTE", cat: .editing,
             isA: "A very quiet hit (velocity 20–45) between the real ones.",
             does: "Adds texture and forward motion without being heard as a separate hit.",
             when: "Snares either side of the backbeat in boom bap, funk and R&B.",
             related: ["velocity", "groove", "pocket"]),

        Term(id: "humanize", name: "HUMANIZE / RANDOMIZE", cat: .editing,
             isA: "Small random offsets to timing and velocity.",
             does: "Nudges notes off the perfect grid so they sound played rather than programmed.",
             when: "On hats and percussion. ±10–15 velocity, ±5 ms timing. More than that reads as a mistake.",
             related: ["velocity", "quantize", "groove"]),

        Term(id: "swing", name: "SWING / SHUFFLE", cat: .editing,
             isA: "Delaying every second subdivision.",
             does: "Pushes the off-16ths late so the rhythm lopes instead of marching.",
             when: "8–15% on almost anything modern. 25–40% for boom bap and lo-fi. 0% for drill and techno.",
             found: [DAWLocation(daw: "ABLETON", path: "Groove Pool, or the Swing amount in the quantize dialog"),
                     DAWLocation(daw: "FL STUDIO", path: "Global Shuffle knob, or per-channel swing"),
                     DAWLocation(daw: "LOGIC", path: "Quantize menu → swing presets 8A–8F / 16A–16F")],
             related: ["groove", "quantize", "pocket"]),

        Term(id: "groove", name: "GROOVE TEMPLATE", cat: .editing,
             isA: "A saved timing-and-velocity fingerprint.",
             does: "Applies another performance's feel to your programmed notes.",
             when: "Drag an MPC or J Dilla groove onto stiff hats. Instant pocket, zero theory.",
             related: ["swing", "quantize", "pocket", "humanize"]),

        Term(id: "pocket", name: "POCKET", cat: .editing,
             isA: "The feeling that a groove is sitting exactly right.",
             does: "Comes from small timing relationships — a late snare, early hats, a dead-on kick.",
             when: "What you're chasing when a pattern is technically correct but doesn't move you.",
             related: ["swing", "groove", "ghostNote"]),

        Term(id: "subdivision", name: "SUBDIVISION", cat: .editing,
             isA: "How finely a beat is split.",
             does: "Quarters, eighths, sixteenths, triplets. Controls perceived speed.",
             when: "Choosing your hat rhythm. Sixteenths feel twice as fast as eighths at the same tempo.",
             related: ["bar", "roll", "hihat"]),

        Term(id: "roll", name: "ROLL", cat: .editing,
             isA: "A fast burst of repeated hits.",
             does: "Subdivides faster than the main pattern for a short moment.",
             when: "End of a bar or phrase, ramping velocity upward into the next section. One per four bars.",
             related: ["fill", "hihat", "subdivision"]),

        Term(id: "chop", name: "CHOP / SLICE", cat: .editing,
             isA: "Cutting a sample into pieces mapped to keys or pads.",
             does: "Turns one audio file into an instrument you can replay in any order.",
             when: "Sampling. Slice at transients, then rearrange — the rearranging is the creative act.",
             found: [DAWLocation(daw: "ABLETON", path: "Right-click audio clip → Slice to New MIDI Track"),
                     DAWLocation(daw: "FL STUDIO", path: "Slicex or Edison → slice, drag to playlist"),
                     DAWLocation(daw: "LOGIC", path: "Quick Sampler → Slice mode")],
             related: ["sampler", "transient", "warp", "audioTrack"]),

        Term(id: "transient", name: "TRANSIENT", cat: .editing,
             isA: "The initial spike at the start of a sound.",
             does: "Carries the attack and most of the perceived punch. The click of a kick, the crack of a snare.",
             when: "Slice just BEFORE it, never after. Compressor attack times are entirely about whether you keep it.",
             related: ["chop", "attack", "compressor"]),

        Term(id: "warp", name: "WARP / FLEX / ELASTIC", cat: .editing,
             aka: ["time stretch", "elastic audio"],
             isA: "Stretching audio to a different tempo without changing pitch.",
             does: "Analyses the transients and rubber-bands the audio onto your grid.",
             when: "Any time you import a loop or sample recorded at a different tempo.",
             found: [DAWLocation(daw: "ABLETON", path: "Clip view → Warp toggle + mode (Beats/Complex Pro)"),
                     DAWLocation(daw: "FL STUDIO", path: "Channel settings → Time stretching mode"),
                     DAWLocation(daw: "LOGIC", path: "Flex Time — track header scissors icon")],
             related: ["timeStretch", "audioTrack", "bpm"]),

        Term(id: "timeStretch", name: "TIME STRETCH", cat: .editing,
             isA: "Changing length without changing pitch.",
             does: "The algorithm matters — 'Beats' or 'Rhythmic' for drums, 'Complex'/'Polyphonic' for full mixes and vocals.",
             when: "Fitting a sample to your tempo. Beyond ±20% it starts sounding obviously processed.",
             related: ["warp", "chop"]),

        Term(id: "automation", name: "AUTOMATION", cat: .arrange,
             isA: "A recorded movement of a control over time.",
             does: "Draws a curve that moves a fader, knob or parameter as the song plays.",
             when: "Filter sweeps in a build, fading a pad in, riding a vocal, 808 pitch slides.",
             found: [DAWLocation(daw: "ABLETON", path: "A key toggles automation mode"),
                     DAWLocation(daw: "FL STUDIO", path: "Right-click any knob → Create automation clip"),
                     DAWLocation(daw: "LOGIC", path: "A key shows lanes, pick the parameter in the track header")],
             related: ["envelope", "modulation", "filter", "arrangement"]),

        // MARK: Arrangement

        Term(id: "arrangement", name: "ARRANGEMENT", cat: .arrange,
             aka: ["playlist", "timeline", "song view"],
             isA: "The left-to-right timeline of the finished song.",
             does: "Where loops become sections and sections become a track.",
             when: "Once your 4-bar loop is good. Duplicate it across the length, then mute things back out.",
             found: [DAWLocation(daw: "ABLETON", path: "Arrangement View — Tab key"),
                     DAWLocation(daw: "FL STUDIO", path: "Playlist — F5"),
                     DAWLocation(daw: "LOGIC", path: "The main workspace")],
             related: ["section", "clip", "drop", "build"]),

        Term(id: "section", name: "SECTION", cat: .arrange,
             isA: "A named chunk of the song — intro, verse, hook, bridge, outro.",
             does: "Groups 8 or 16 bars that share the same energy and instrumentation.",
             when: "Planning structure. Mark them with locators so you can jump around while working.",
             related: ["arrangement", "bar", "drop"]),

        Term(id: "drop", name: "DROP", cat: .arrange,
             isA: "The moment of maximum energy.",
             does: "Everything arrives at once after a build has taken things away.",
             when: "It only works because of what came before. Strip the bar before it and the drop hits twice as hard.",
             related: ["build", "transition", "arrangement"]),

        Term(id: "build", name: "BUILD / PRE", cat: .arrange,
             aka: ["riser section", "pre-chorus"],
             isA: "The 4–8 bars that raise tension before a drop.",
             does: "Removes the kick, adds risers, closes a filter, ramps velocity.",
             when: "Before every big section change. It's what makes the change feel earned.",
             related: ["riser", "drop", "transition", "automation"]),

        Term(id: "transition", name: "TRANSITION", cat: .arrange,
             isA: "The glue between two sections.",
             does: "A crash, a riser, a fill, a filter sweep or a beat of silence marking the seam.",
             when: "At every section boundary. Pick two techniques for big moments, one for small.",
             related: ["riser", "fill", "build", "drop"]),

        Term(id: "riser", name: "RISER / UPLIFTER", cat: .arrange,
             isA: "A sound that climbs in pitch or brightness.",
             does: "Creates rising tension over 1–4 bars.",
             when: "Leading into a drop. Pair with a downlifter or crash landing ON the new section.",
             related: ["transition", "build", "drop"]),

        Term(id: "fill", name: "FILL", cat: .arrange,
             isA: "A short drum flurry at the end of a phrase.",
             does: "Signals a change is coming and pushes into the next section.",
             when: "Last half-bar of every 4 or 8. Must land on something that actually changes.",
             related: ["roll", "transition", "arrangement"]),

        // MARK: Theory / musical

        Term(id: "key", name: "KEY", cat: .theory,
             isA: "The home note of a piece plus the set of notes that work with it.",
             does: "Eliminates five of the twelve notes, leaving the ones that sound right together.",
             when: "Before writing anything melodic. Turn on scale highlighting and you can't play a wrong note.",
             related: ["scale", "rootNote", "transpose", "chord"]),

        Term(id: "scale", name: "SCALE", cat: .theory,
             isA: "The pattern of steps defining a key.",
             does: "Minor is dark, major is bright, dorian is minor with one bright note, phrygian is menacing.",
             when: "Pick minor unless you want happy. Pentatonic if you're stuck — five notes that can't clash.",
             related: ["key", "pentatonic", "rootNote"]),

        Term(id: "pentatonic", name: "PENTATONIC", cat: .theory,
             isA: "A five-note scale.",
             does: "Removes the two notes most likely to clash, leaving a melody-proof set.",
             when: "When a melody keeps sounding wrong and you don't know why.",
             related: ["scale", "melody", "key"]),

        Term(id: "rootNote", name: "ROOT NOTE", cat: .theory,
             aka: ["tonic", "key centre"],
             isA: "The home note everything resolves to.",
             does: "The note a chord is built from, and the note a bassline usually plays.",
             when: "Finding a sample's key: play notes against it until one disappears into it. That's the root.",
             related: ["key", "chord", "bass"]),

        Term(id: "transpose", name: "TRANSPOSE / PITCH", cat: .theory,
             isA: "Moving notes or audio up or down in semitones.",
             does: "+12 or −12 is an octave, same note. Anything else changes the key.",
             when: "Matching a sample to your key, or moving a part into a range where it doesn't fight something else.",
             related: ["octave", "key", "sampler"]),

        Term(id: "octave", name: "OCTAVE", cat: .theory,
             isA: "Twelve semitones — the same note, higher or lower.",
             does: "Doubles or halves the frequency. Sounds like the same note in a different register.",
             when: "Separating parts. Melody an octave above the chords keeps both audible.",
             related: ["transpose", "pianoRoll"]),

        Term(id: "chord", name: "CHORD", cat: .theory,
             isA: "Three or more notes at once.",
             does: "Minor = root, +3, +7. Major = root, +4, +7. One semitone is the whole distance between sad and happy.",
             when: "The harmonic bed under everything. One chord per bar is the safe default.",
             related: ["triad", "inversion", "progression", "voicing"]),

        Term(id: "triad", name: "TRIAD", cat: .theory,
             isA: "A three-note chord.",
             does: "Root, third, fifth. The third decides major or minor; the fifth is neutral filler.",
             when: "The starting point for every chord. Add a 7th for smoothness once it feels plain.",
             related: ["chord", "inversion"]),

        Term(id: "inversion", name: "INVERSION", cat: .theory,
             isA: "The same chord with its notes reordered.",
             does: "Move the lowest note up an octave — same chord, different position on the roll.",
             when: "So consecutive chords stay close together instead of leaping. This is voice leading.",
             related: ["chord", "voicing", "voiceLeading"]),

        Term(id: "voicing", name: "VOICING", cat: .theory,
             isA: "How a chord's notes are spaced.",
             does: "Wide spacing sounds open, tight clusters sound tense, low clusters sound muddy.",
             when: "Keep chords above C3. Want low weight? Add a single bass note, don't drop the chord.",
             related: ["chord", "inversion", "mud"]),

        Term(id: "voiceLeading", name: "VOICE LEADING", cat: .theory,
             isA: "Moving between chords by the smallest possible distance.",
             does: "Keeps shared notes in place and moves the rest one or two semitones.",
             when: "Any time a progression sounds blocky rather than flowing.",
             related: ["inversion", "progression", "chord"]),

        Term(id: "progression", name: "PROGRESSION", cat: .theory,
             isA: "A repeating order of chords.",
             does: "Creates the loop's emotional arc. i–VI–III–VII is the most used in modern music.",
             when: "Four chords over four or eight bars. Change on the bar, not inside it.",
             related: ["chord", "degree", "key"]),

        Term(id: "degree", name: "SCALE DEGREE", cat: .theory,
             aka: ["roman numerals"],
             isA: "A chord's position in the key, written I–VII.",
             does: "Lets a progression be written once and used in any key. Lowercase = minor, uppercase = major.",
             when: "Reading progressions online. i–VI–III–VII in A minor is Am–F–C–G.",
             related: ["progression", "chord", "key"]),

        Term(id: "arpeggio", name: "ARPEGGIO / ARP", cat: .theory,
             isA: "A chord played one note at a time.",
             does: "Turns static harmony into movement without changing the chords.",
             when: "When a pad is too static. An arpeggiator plugin does it automatically from held notes.",
             related: ["chord", "melody", "pad"]),

        Term(id: "melody", name: "MELODY", cat: .theory,
             isA: "A sequence of single notes that carries the tune.",
             does: "The part people remember and hum back.",
             when: "Four to eight notes, repeated with a changed ending, with gaps between phrases.",
             related: ["hook", "motif", "callResponse", "scale"]),

        Term(id: "hook", name: "HOOK", cat: .theory,
             isA: "The most memorable phrase in the track.",
             does: "Short, repeated, and usually the highest or most distinctive sound in the mix.",
             when: "If you can't hum it after two listens, it isn't a hook yet.",
             related: ["melody", "motif"]),

        Term(id: "motif", name: "MOTIF", cat: .theory,
             isA: "A short musical idea reused across a track.",
             does: "Gives a song identity through repetition and variation.",
             when: "Take a 3–4 note idea and restate it in different octaves, instruments and rhythms.",
             related: ["melody", "hook"]),

        Term(id: "callResponse", name: "CALL & RESPONSE", cat: .theory,
             isA: "A phrase answered by a different phrase.",
             does: "Creates conversation and leaves gaps, which is what makes phrases memorable.",
             when: "Melody in bars 1–2, answer in bars 3–4. Or a vocal and an instrumental fill trading.",
             related: ["melody", "hook", "arrangement"]),

        // MARK: Drum vocabulary

        Term(id: "kick", name: "KICK / BD", cat: .theory,
             aka: ["bass drum", "808"],
             isA: "The lowest drum. The floor of the beat.",
             does: "Sets the pulse and owns everything below 100 Hz.",
             when: "First element you place. Two per bar to start; add a third only if it feels empty.",
             related: ["808", "sidechain", "fourOnTheFloor", "bass"]),

        Term(id: "snare", name: "SNARE", cat: .theory,
             isA: "The backbeat drum.",
             does: "Answers the kick, usually on beats 2 and 4, and defines where the bar sits.",
             when: "Second element. Half-time genres put it on beat 3 only.",
             related: ["backbeat", "halfTime", "ghostNote", "clap"]),

        Term(id: "clap", name: "CLAP", cat: .theory,
             isA: "A wider, brighter backbeat sound.",
             does: "Several noise bursts a few ms apart, which is why it sounds like a crowd rather than a hit.",
             when: "Layered with the snare for width, or instead of it in house and pop.",
             related: ["snare", "layering", "backbeat"]),

        Term(id: "hihat", name: "HI-HAT", cat: .theory,
             isA: "The fast, quiet, high-frequency drum.",
             does: "Subdivides the bar and sets how fast the music feels.",
             when: "Third element. Eighths is the safe default; sixteenths for trap and dance.",
             related: ["openHat", "subdivision", "roll", "velocity"]),

        Term(id: "openHat", name: "OPEN HAT", cat: .theory,
             isA: "A hi-hat left to ring out.",
             does: "Adds air and lift, and pushes the bar forward.",
             when: "One per bar, usually on an off-beat or on step 15 leading back to the top.",
             related: ["hihat", "subdivision"]),

        Term(id: "backbeat", name: "BACKBEAT", cat: .theory,
             isA: "The snare on beats 2 and 4.",
             does: "The head-nod. Almost universal in popular music.",
             when: "Default snare placement. Deviating from it is a genre decision, not a random one.",
             related: ["snare", "halfTime"]),

        Term(id: "halfTime", name: "HALF-TIME", cat: .theory,
             isA: "One snare per bar instead of two.",
             does: "Makes a fast tempo feel slow and heavy without changing the BPM.",
             when: "Trap, drill, dubstep. It's why 140 BPM trap feels like 70.",
             related: ["backbeat", "snare", "bpm"]),

        Term(id: "fourOnTheFloor", name: "FOUR ON THE FLOOR", cat: .theory,
             isA: "A kick on every beat.",
             does: "Creates a constant, hypnotic pulse.",
             when: "House, techno, disco, a lot of pop. Pair with off-beat open hats for the classic lift.",
             related: ["kick", "openHat", "bpm"])
    ]
}
